-- test/geo2d/curve_test.lua

local h     = require("test.harness")
local curve = require("jnl.geo2d.curve")

local function near(a, b, eps)
	return math.abs(a - b) <= (eps or 1e-9)
end

h.describe("curve.line", function()
	h.it("kind is 'line'", function()
		h.expect(curve.line(0, 0, 1, 0):kind()).equals("line")
	end)

	h.it("3-4-5 triangle has length 5", function()
		h.expect(near(curve.line(0, 0, 3, 4):length(), 5)).is_truthy()
	end)

	h.it("start and finish match construction args", function()
		local c = curve.line(1, 2, 3, 4)
		local s, f = c:start(), c:finish()
		h.expect(s[1]).equals(1); h.expect(s[2]).equals(2)
		h.expect(f[1]).equals(3); h.expect(f[2]).equals(4)
	end)

	h.it("eval at 0.5 gives midpoint", function()
		local p = curve.line(0, 0, 2, 0):eval(0.5)
		h.expect(near(p[1], 1)).is_truthy()
		h.expect(near(p[2], 0)).is_truthy()
	end)
end)

h.describe("curve.arc", function()
	h.it("kind is 'arc'", function()
		h.expect(curve.arc(0, 0, 1, 0, math.pi):kind()).equals("arc")
	end)

	h.it("quarter circle length is pi * r", function()
		h.expect(near(curve.arc(0, 0, 2, 0, math.pi / 2):length(), math.pi)).is_truthy()
	end)

	h.it("start lies on circle", function()
		local s = curve.arc(0, 0, 1, 0, math.pi / 2):start()
		h.expect(near(math.sqrt(s[1] ^ 2 + s[2] ^ 2), 1)).is_truthy()
	end)
end)

h.describe("curve.polyline", function()
	h.it("kind is 'polyline'", function()
		h.expect(curve.polyline({ { 0, 0 }, { 1, 0 }, { 1, 1 } }):kind()).equals("polyline")
	end)

	h.it("L-shape has length 7", function()
		h.expect(near(curve.polyline({ { 0, 0 }, { 3, 0 }, { 3, 4 } }):length(), 7)).is_truthy()
	end)

	h.it("fewer than two points errors", function()
		h.expect(function() curve.polyline({ { 0, 0 } }) end).throws()
	end)
end)

h.describe("curve.chain", function()
	h.it("kind is 'chain'", function()
		local c = curve.chain({ curve.line(0, 0, 1, 0), curve.line(1, 0, 1, 1) })
		h.expect(c:kind()).equals("chain")
	end)

	h.it("length is sum of children", function()
		local c = curve.chain({ curve.line(0, 0, 3, 0), curve.line(3, 0, 3, 4) })
		h.expect(near(c:length(), 7)).is_truthy()
	end)

	h.it("start and finish delegate to first and last child", function()
		local c = curve.chain({ curve.line(0, 0, 1, 0), curve.line(1, 0, 2, 1) })
		local s, f = c:start(), c:finish()
		h.expect(near(s[1], 0)).is_truthy(); h.expect(near(s[2], 0)).is_truthy()
		h.expect(near(f[1], 2)).is_truthy(); h.expect(near(f[2], 1)).is_truthy()
	end)
end)

h.describe("clone and reversal", function()
	h.it("clone is a distinct object with equal length", function()
		local a = curve.line(0, 0, 1, 0)
		local b = a:clone()
		h.expect(a).not_equals(b)
		h.expect(near(b:length(), a:length())).is_truthy()
	end)

	h.it("reversed swaps start and finish", function()
		local a = curve.line(1, 2, 3, 4)
		local b = a:reversed()
		local s, f = a:start(), b:finish()
		h.expect(near(f[1], s[1])).is_truthy()
		h.expect(near(f[2], s[2])).is_truthy()
	end)

	h.it("reverse_inplace returns self", function()
		local c = curve.line(0, 0, 1, 0)
		h.expect(c:reverse_inplace()).equals(c)
	end)

	h.it("reversed preserves length", function()
		local a = curve.line(1, 2, 3, 4)
		h.expect(near(a:reversed():length(), a:length())).is_truthy()
	end)
end)

h.describe("curve.between", function()
	h.it("accepts point tables", function()
		local c = curve.between({ 0, 0 }, { 1, 1 })
		h.expect(c:kind()).equals("line")
		h.expect(near(c:length(), math.sqrt(2))).is_truthy()
	end)
end)

h.describe("curve.rectangle", function()
	h.it("is a chain", function()
		h.expect(curve.rectangle(0, 0, 2, 1):kind()).equals("chain")
	end)

	h.it("perimeter is correct", function()
		h.expect(near(curve.rectangle(0, 0, 3, 4):length(), 14)).is_truthy()
	end)

	h.it("is closed", function()
		local c = curve.rectangle(0, 0, 1, 1)
		local s, f = c:start(), c:finish()
		h.expect(near(s[1], f[1])).is_truthy()
		h.expect(near(s[2], f[2])).is_truthy()
	end)

	h.it("normalises inverted corners", function()
		local c1 = curve.rectangle(0, 0, 2, 1)
		local c2 = curve.rectangle(2, 1, 0, 0)
		h.expect(near(c1:length(), c2:length())).is_truthy()
	end)
end)

h.describe("curve.circle", function()
	h.it("is a chain", function()
		h.expect(curve.circle({ 0, 0 }, 1):kind()).equals("chain")
	end)

	h.it("circumference is 2*pi*r", function()
		h.expect(near(curve.circle({ 0, 0 }, 3):length(), 6 * math.pi, 1e-6)).is_truthy()
	end)

	h.it("is closed", function()
		local c = curve.circle({ 1, 2 }, 0.5)
		local s, f = c:start(), c:finish()
		h.expect(near(s[1], f[1], 1e-9)).is_truthy()
		h.expect(near(s[2], f[2], 1e-9)).is_truthy()
	end)
end)

h.describe("curve.through", function()
	h.it("produces a polyline", function()
		h.expect(curve.through({ { 0, 0 }, { 1, 0 }, { 2, 1 } }):kind()).equals("polyline")
	end)

	h.it("fewer than two points errors", function()
		h.expect(function() curve.through({ { 0, 0 } }) end).throws()
	end)
end)

h.describe("curve.closed_polyline", function()
	h.it("closes an open sequence", function()
		local c = curve.closed_polyline({ { 0, 0 }, { 1, 0 }, { 1, 1 } })
		local s, f = c:start(), c:finish()
		h.expect(near(s[1], f[1])).is_truthy()
		h.expect(near(s[2], f[2])).is_truthy()
	end)

	h.it("does not duplicate an already-closed sequence", function()
		h.expect(function()
			curve.closed_polyline({ { 0, 0 }, { 1, 0 }, { 1, 1 }, { 0, 0 } })
		end).not_throws()
	end)

	h.it("fewer than three points errors", function()
		h.expect(function() curve.closed_polyline({ { 0, 0 }, { 1, 0 } }) end).throws()
	end)
end)

h.describe("curve.join", function()
	h.it("single non-nil curve is cloned", function()
		local a = curve.line(0, 0, 1, 0)
		local b = curve.join({ a })
		h.expect(b).not_equals(a)
		h.expect(near(b:length(), a:length())).is_truthy()
	end)

	h.it("two curves form a chain", function()
		local c = curve.join({ curve.line(0, 0, 1, 0), curve.line(1, 0, 1, 1) })
		h.expect(c:kind()).equals("chain")
	end)

	h.it("nil entries are filtered", function()
		h.expect(function()
			curve.join({ curve.line(0, 0, 1, 0), nil, curve.line(1, 0, 1, 1) })
		end).not_throws()
	end)

	h.it("all-nil table errors", function()
		h.expect(function() curve.join({}) end).throws()
	end)
end)

h.describe("curve.translate", function()
	h.it("shifts start point", function()
		local s = curve.translate(curve.line(0, 0, 1, 0), 3, 5):start()
		h.expect(near(s[1], 3)).is_truthy()
		h.expect(near(s[2], 5)).is_truthy()
	end)

	h.it("preserves length", function()
		local c = curve.line(0, 0, 1, 0)
		h.expect(near(curve.translate(c, 10, -5):length(), c:length())).is_truthy()
	end)
end)

h.describe("curve.scale", function()
	h.it("scales length proportionally", function()
		h.expect(near(curve.scale(curve.line(0, 0, 1, 0), 3):length(), 3)).is_truthy()
	end)

	h.it("asymmetric scale with two factors", function()
		local f = curve.scale(curve.line(0, 0, 1, 0), 2, 5):finish()
		h.expect(near(f[1], 2)).is_truthy()
		h.expect(near(f[2], 0)).is_truthy()
	end)
end)

h.describe("curve.rotate", function()
	h.it("90° rotation maps (1,0) finish to (0,1)", function()
		local f = curve.rotate(curve.line(0, 0, 1, 0), math.pi / 2):finish()
		h.expect(near(f[1], 0, 1e-6)).is_truthy()
		h.expect(near(f[2], 1, 1e-6)).is_truthy()
	end)

	h.it("preserves length", function()
		local c = curve.line(0, 0, 1, 0)
		h.expect(near(curve.rotate(c, 1.23):length(), c:length(), 1e-6)).is_truthy()
	end)
end)

h.describe("distributions", function()
	h.it("uniform kind", function()
		h.expect(curve.uniform():kind()).equals("uniform")
	end)

	h.it("cosine_both kind", function()
		h.expect(curve.cosine_both():kind()).equals("cosine_both")
	end)

	h.it("geom_start kind", function()
		h.expect(curve.geom_start(2):kind()).equals("geom_start")
	end)

	h.it("geom_end kind", function()
		h.expect(curve.geom_end(2):kind()).equals("geom_end")
	end)

	h.it("geom_start ratio <= 0 errors", function()
		h.expect(function() curve.geom_start(0) end).throws()
	end)
end)

h.describe("sampling", function()
	h.it("returns n points", function()
		h.expect(#curve.sample(curve.line(0, 0, 1, 0), 5)).equals(5)
	end)

	h.it("first and last points match start and finish", function()
		local c   = curve.line(1, 2, 3, 4)
		local pts = curve.sample(c, 5)
		h.expect(near(pts[1][1], 1)).is_truthy()
		h.expect(near(pts[5][1], 3)).is_truthy()
	end)

	h.it("sample_closed returns n points without seam repeat", function()
		local pts = curve.sample_closed(curve.rectangle(0, 0, 1, 1), 8)
		h.expect(#pts).equals(8)
		local d = math.sqrt((pts[1][1] - pts[8][1]) ^ 2 + (pts[1][2] - pts[8][2]) ^ 2)
		h.expect(d > 1e-6).is_truthy("seam point should not be repeated")
	end)
end)
