-- test/geo2d/domain_test.lua

local h = require("test.harness")
local pen = require("jnl.geo2d.pen")
local domain = require("jnl.geo2d.domain")

local function rect_pen()
    return pen.new():at(0, 0):east(2):north(1):west(2):close()
end

local function tagged_pen()
    return pen.new()
        :at(0, 0)
        :east(2)
        :tag("bottom")
        :north(1)
        :tag("right")
        :west(2)
        :tag("top")
        :close()
end

h.describe("domain.from_pen basics", function()
    h.it("returns a domain and a registry", function()
        local d, reg = domain.from_pen(rect_pen())
        h.expect(d).is_not_nil()
        h.expect(reg).is_not_nil()
    end)

    h.it("untagged pen has no patches", function()
        local d, _ = domain.from_pen(rect_pen())
        h.expect(d:n_patches()).equals(0)
    end)

    h.it("each tagged segment becomes a patch", function()
        local d, _ = domain.from_pen(tagged_pen())
        h.expect(d:n_patches()).equals(3)
    end)

    h.it("accepts a custom default name", function()
        h.expect(function()
            domain.from_pen(rect_pen(), { default = "noslip" })
        end).not_throws()
    end)
end)

h.describe("marker registry", function()
    h.it("each distinct name gets a unique marker", function()
        local _, reg = domain.from_pen(tagged_pen())
        local mb = reg:get("bottom")
        local mr = reg:get("right")
        local mt = reg:get("top")
        h.expect(mb).not_equals(mr)
        h.expect(mr).not_equals(mt)
        h.expect(mb).not_equals(mt)
    end)

    h.it("same name always returns the same marker", function()
        local _, reg = domain.from_pen(rect_pen())
        h.expect(reg:get("inlet")).equals(reg:get("inlet"))
    end)

    h.it("markers are positive integers", function()
        local _, reg = domain.from_pen(rect_pen())
        local m = reg:get("whatever")
        h.expect(type(m)).equals("number")
        h.expect(m > 0).is_truthy()
        h.expect(math.floor(m) == m).is_truthy()
    end)

    h.it("default patch name is pre-allocated in registry", function()
        local _, reg = domain.from_pen(rect_pen())
        -- 'wall' is the default; it must already be in the registry.
        -- Calling get() a second time should return the same value,
        -- not a new one.
        local m1 = reg:get("wall")
        local m2 = reg:get("wall")
        h.expect(m1).equals(m2)
    end)

    h.it("custom default is pre-allocated in registry", function()
        local _, reg = domain.from_pen(rect_pen(), { default = "symmetry" })
        local m = reg:get("symmetry")
        h.expect(m > 0).is_truthy()
    end)

    h.it("tags and default occupy different markers", function()
        local _, reg = domain.from_pen(tagged_pen())
        local mwall = reg:get("wall")
        local mbottom = reg:get("bottom")
        h.expect(mwall).not_equals(mbottom)
    end)
end)

h.describe("hints stored on pen segments", function()
    -- Hints live on pen.segs, not on the domain object, so these tests
    -- do not touch the C userdata and are unconditionally safe.

    h.it("hint n is stored on the tagged segment", function()
        local p = pen.new()
            :at(0, 0)
            :east(2)
            :tag("bottom")
            :hint({ n = 48 })
            :north(1)
            :tag("right")
            :west(2)
            :close()
        h.expect(p.segs[1].hint).is_not_nil()
        h.expect(p.segs[1].hint.n).equals(48)
    end)

    h.it("hint is nil when not set", function()
        local p = pen.new():at(0, 0):east(1):tag("a")
        h.expect(p.segs[1].hint).is_nil()
    end)

    h.it("hint on one segment does not bleed to adjacent segments", function()
        local p = pen.new()
            :at(0, 0)
            :east(1)
            :tag("a")
            :hint({ n = 64 })
            :north(1)
            :tag("b")
        h.expect(p.segs[1].hint).is_not_nil()
        h.expect(p.segs[2].hint).is_nil()
    end)
end)

h.describe("domain2d methods smoke test", function()
    -- Verify the core C methods are callable after construction.

    h.it(":n_holes() returns 0 on a fresh domain", function()
        local d, _ = domain.from_pen(rect_pen())
        h.expect(d:n_holes()).equals(0)
    end)

    h.it(":n_regions() returns 0 on a fresh domain", function()
        local d, _ = domain.from_pen(rect_pen())
        h.expect(d:n_regions()).equals(0)
    end)

    h.it(":bbox() returns a table with four keys", function()
        local d, _ = domain.from_pen(rect_pen())
        local bb = d:bbox()
        h.expect(type(bb.min_x)).equals("number")
        h.expect(type(bb.min_y)).equals("number")
        h.expect(type(bb.max_x)).equals("number")
        h.expect(type(bb.max_y)).equals("number")
    end)

    h.it(":bbox() extents match the pen geometry", function()
        local d, _ = domain.from_pen(rect_pen())
        local bb = d:bbox()
        -- rect_pen is 2 wide by 1 tall from (0,0)
        h.expect(bb.min_x < 0.01).is_truthy()
        h.expect(bb.max_x > 1.9).is_truthy()
        h.expect(bb.max_y > 0.9).is_truthy()
    end)

    h.it(":contains() finds an interior point", function()
        local d, _ = domain.from_pen(rect_pen())
        h.expect(d:contains({ 1.0, 0.5 })).is_truthy()
    end)

    h.it(":contains() rejects an exterior point", function()
        local d, _ = domain.from_pen(rect_pen())
        h.expect(d:contains({ 5.0, 5.0 })).is_falsy()
    end)

    h.it(":check() passes for a valid rectangle domain", function()
        local d, _ = domain.from_pen(rect_pen())
        local ok, err = d:check()
        h.expect(ok).is_truthy(err or "check failed")
    end)
end)
