#ifndef TRIANGLE_VERSION_H
#define TRIANGLE_VERSION_H

/* #undef TRIANGLE_ENABLE_ACUTE */  // or comment out if you don't want acute

#define TRIANGLE_VERSION "1.7.0"
#define TRIANGLE_VERSION_MAJOR 1
#define TRIANGLE_VERSION_MINOR 7
#define TRIANGLE_VERSION_PATCH 0
#define TRIANGLE_VERSION_INT ((TRIANGLE_VERSION_MAJOR * 100 + TRIANGLE_VERSION_MINOR) * 100 + TRIANGLE_VERSION_PATCH)

#endif
