local h = require("test.harness")
local Node = require("jnl.nabla.node")

h.describe("ops.grad linearisation", function()
	local ops = require("jnl.nabla.ops")
	local p   = Node.scalar("p")
	local nu  = Node.scalar("nu")
	local U   = Node.vector("U")

	h.it("grad(scalar) produces rank-1 grad node", function()
		local n = ops.grad(p)
		h.expect(n.kind).equals("grad")
		h.expect(n.rank).equals(1)
		h.expect(n.a).equals(p)
	end)

	h.it("grad(vector) produces rank-2 grad node", function()
		local n = ops.grad(U)
		h.expect(n.kind).equals("grad")
		h.expect(n.rank).equals(2)
	end)

	h.it("grad(-scalar) → neg(grad(scalar))", function()
		local n = ops.grad(-p)
		h.expect(n.kind).equals("neg")
		h.expect(n.a.kind).equals("grad")
		h.expect(n.a.rank).equals(1)
		h.expect(n.a.a).equals(p)
	end)

	h.it("grad(-vector) → neg(grad(vector)), rank 2", function()
		local n = ops.grad(-U)
		h.expect(n.kind).equals("neg")
		h.expect(n.a.kind).equals("grad")
		h.expect(n.a.rank).equals(2)
	end)

	h.it("grad(nu * p) → scale(nu, grad(p))", function()
		local n = ops.grad(nu * p)
		h.expect(n.kind).equals("scale")
		h.expect(n.rank).equals(1)
		h.expect(n.a).equals(nu)
		h.expect(n.b.kind).equals("grad")
		h.expect(n.b.a).equals(p)
	end)

	h.it("grad(nu * U) → scale(nu, grad(U)), rank 2", function()
		local n = ops.grad(nu * U)
		h.expect(n.kind).equals("scale")
		h.expect(n.rank).equals(2)
		h.expect(n.a).equals(nu)
		h.expect(n.b.kind).equals("grad")
		h.expect(n.b.rank).equals(2)
	end)

	h.it("grad(tensor) errors", function()
		local T = Node.tensor("T")
		h.expect(function() ops.grad(T) end).throws()
	end)
end)
