local h = require("test.harness")
local Node = require("jnl.nabla.node")
local resolve = require("jnl.nabla.resolve")
local ops = require("jnl.nabla.ops")

h.describe("resolve: scalar field", function()
	h.it("scalar symbol resolves to itself (rank-0)", function()
		local p = Node.scalar("p")
		local r = resolve.resolve(p, 2)
		h.expect(Node.is_node(r)).is_truthy()
		h.expect(r.rank).equals(0)
		h.expect(r.name).equals("p")
	end)

	h.it("scalar arithmetic resolves to scalar", function()
		local p = Node.scalar("p")
		local q = Node.scalar("q")
		local r = resolve.resolve(p + q, 2)
		h.expect(r.rank).equals(0)
	end)

	h.it("anon constant resolves to itself", function()
		local c = Node.const(3.14)
		local r = resolve.resolve(c, 2)
		h.expect(r.kind).equals("constant")
		h.expect(r.a).equals(3.14)
	end)
end)

h.describe("resolve: vector to components", function()
	h.it("vector resolves to array of 2 scalars in 2D", function()
		local U = Node.vector("U")
		local r = resolve.resolve(U, 2)
		h.expect(type(r)).equals("table")
		h.expect(#r).equals(2)
		h.expect(r[1].rank).equals(0)
		h.expect(r[2].rank).equals(0)
	end)

	h.it("component names follow mangle convention U_x, U_y", function()
		local U = Node.vector("U")
		local r = resolve.resolve(U, 2)
		h.expect(r[1].name).equals("U_x")
		h.expect(r[2].name).equals("U_y")
	end)

	h.it("3D vector resolves to 3 components", function()
		local U = Node.vector("U")
		local r = resolve.resolve(U, 3)
		h.expect(#r).equals(3)
		h.expect(r[3].name).equals("U_z")
	end)

	h.it("cvec resolves components to constants", function()
		local g = Node.const("g", 0.0, -9.81)
		local r = resolve.resolve(g, 2)
		h.expect(#r).equals(2)
		h.expect(r[1].kind).equals("constant")
		h.expect(r[1].a).equals(0.0)
		h.expect(r[2].kind).equals("constant")
		h.expect(r[2].a).equals(-9.81)
	end)
end)

h.describe("resolve: tensor to components", function()
	h.it("rank-2 tensor resolves to ndims x ndims table", function()
		local T = Node.tensor("T")
		local r = resolve.resolve(T, 2)
		h.expect(type(r)).equals("table")
		h.expect(#r).equals(2)
		h.expect(#r[1]).equals(2)
	end)

	h.it("component names follow mangle convention T_xy", function()
		local T = Node.tensor("T")
		local r = resolve.resolve(T, 2)
		h.expect(r[1][1].name).equals("T_xx")
		h.expect(r[1][2].name).equals("T_xy")
		h.expect(r[2][1].name).equals("T_yx")
	end)
end)

h.describe("resolve: equation", function()
	h.it("scalar equation resolves to 1-element list", function()
		local p  = Node.scalar("p")
		local q  = Node.scalar("q")
		local eq = p:equals(q)
		local r  = resolve.resolve_equation(eq, 2)
		h.expect(#r).equals(1)
	end)

	h.it("vector equation resolves to ndims equations", function()
		local U = Node.vector("U")
		local V = Node.vector("V")
		local r = resolve.resolve_equation(U:equals(V), 2)
		h.expect(#r).equals(2)
	end)

	h.it("resolved equation sides are rank-0", function()
		local U = Node.vector("U")
		local V = Node.vector("V")
		local r = resolve.resolve_equation(U:equals(V), 2)
		h.expect(r[1].lhs.rank).equals(0)
		h.expect(r[1].rhs.rank).equals(0)
	end)

	h.it("rank mismatch in equation errors", function()
		local s = Node.scalar("p")
		local v = Node.vector("U")
		h.expect(function()
			resolve.resolve_equation(s:equals(v), 2)
		end).throws()
	end)
end)

h.describe("resolve: dot product expansion", function()
	h.it("u.v dot produces scalar sum of products", function()
		local u = Node.vector("u")
		local v = Node.vector("v")
		local d = u * v
		h.expect(d.kind).equals("dot")
		local r = resolve.resolve(d, 2)
		h.expect(r.rank).equals(0)
		h.expect(r.kind).not_equals("dot")
	end)

	h.it("2D dot expands to 2 terms", function()
		local u = Node.vector("u")
		local v = Node.vector("v")
		local r = resolve.resolve(u * v, 2)
		-- u_x*v_x + u_y*v_y — top-level should be add
		h.expect(r.kind).equals("add")
	end)
end)

h.describe("resolve: scale distributes", function()
	h.it("scalar * vector component has scalar factor", function()
		local s = Node.scalar("rho")
		local v = Node.vector("U")
		local n = s * v
		h.expect(n.kind).equals("scale")
		local r = resolve.resolve(n, 2)
		h.expect(#r).equals(2)
		h.expect(r[1].rank).equals(0)
	end)
end)

h.describe("resolve: grad produces grad_i nodes", function()
	h.it("grad(scalar) resolves to vector of grad_i nodes", function()
		local p  = Node.scalar("p")
		local gp = ops.grad(p)
		h.expect(gp.rank).equals(1)
		local r = resolve.resolve(gp, 2)
		h.expect(#r).equals(2)
		h.expect(r[1].kind).equals("grad_i")
		h.expect(r[2].kind).equals("grad_i")
	end)

	h.it("grad_i index is correct", function()
		local p  = Node.scalar("p")
		local gp = ops.grad(p)
		local r  = resolve.resolve(gp, 2)
		h.expect(r[1].index).equals(1)
		h.expect(r[2].index).equals(2)
	end)
end)

h.describe("resolve: ddt and laplacian pass through as abstract", function()
	h.it("ddt of scalar stays as ddt node", function()
		local p = Node.scalar("p")
		local d = ops.ddt(p)
		local r = resolve.resolve(d, 2)
		h.expect(r.kind).equals("ddt")
		h.expect(r.rank).equals(0)
	end)

	h.it("laplacian of scalar stays as laplacian node", function()
		local p = Node.scalar("p")
		local l = ops.laplacian(p)
		local r = resolve.resolve(l, 2)
		h.expect(r.kind).equals("laplacian")
		h.expect(r.rank).equals(0)
	end)

	h.it("ddt of vector resolves per component", function()
		local U = Node.vector("U")
		local d = ops.ddt(U)
		local r = resolve.resolve(d, 2)
		h.expect(#r).equals(2)
		h.expect(r[1].kind).equals("ddt")
	end)
end)

h.describe("resolve: ndims validation", function()
	h.it("ndims=1 errors", function()
		local p = Node.scalar("p")
		h.expect(function() resolve.resolve(p, 1) end).throws()
	end)

	h.it("ndims=4 errors", function()
		local p = Node.scalar("p")
		h.expect(function() resolve.resolve(p, 4) end).throws()
	end)
end)
