local h = require("test.harness")
local Node = require("jnl.nabla.node")
local resolve = require("jnl.nabla.resolve")
local ops = require("jnl.nabla.ops")

h.describe("resolve: scalar field", function()
    h.it("scalar symbol resolves to itself (rank-0)", function()
        local p = Node.scalar("p")
        local r = resolve.resolve(p, 2)
        h.expect(Node.is_node(r)).is_truthy()
        h.expect(r.rank).equals(0)
        h.expect(r.name).equals("p")
    end)

    h.it("scalar arithmetic resolves to scalar", function()
        local p = Node.scalar("p")
        local q = Node.scalar("q")
        local r = resolve.resolve(p + q, 2)
        h.expect(r.rank).equals(0)
    end)

    h.it("anon constant resolves to itself", function()
        local c = Node.const(3.14)
        local r = resolve.resolve(c, 2)
        h.expect(r.kind).equals("constant")
        h.expect(r.a).equals(3.14)
    end)
end)

h.describe("resolve: vector to components", function()
    h.it("vector resolves to array of 2 scalars in 2D", function()
        local U = Node.vector("U")
        local r = resolve.resolve(U, 2)
        h.expect(type(r)).equals("table")
        h.expect(#r).equals(2)
        h.expect(r[1].rank).equals(0)
        h.expect(r[2].rank).equals(0)
    end)

    h.it("component names follow mangle convention U_x, U_y", function()
        local U = Node.vector("U")
        local r = resolve.resolve(U, 2)
        h.expect(r[1].name).equals("U_x")
        h.expect(r[2].name).equals("U_y")
    end)

    h.it("3D vector resolves to 3 components", function()
        local U = Node.vector("U")
        local r = resolve.resolve(U, 3)
        h.expect(#r).equals(3)
        h.expect(r[3].name).equals("U_z")
    end)

    h.it("cvec resolves components to constants", function()
        local g = Node.const("g", 0.0, -9.81)
        local r = resolve.resolve(g, 2)
        h.expect(#r).equals(2)
        h.expect(r[1].kind).equals("constant")
        h.expect(r[1].a).equals(0.0)
        h.expect(r[2].kind).equals("constant")
        h.expect(r[2].a).equals(-9.81)
    end)
end)

h.describe("resolve: tensor to components", function()
    h.it("rank-2 tensor resolves to ndims x ndims table", function()
        local T = Node.tensor("T")
        local r = resolve.resolve(T, 2)
        h.expect(type(r)).equals("table")
        h.expect(#r).equals(2)
        h.expect(#r[1]).equals(2)
    end)

    h.it("component names follow mangle convention T_xy", function()
        local T = Node.tensor("T")
        local r = resolve.resolve(T, 2)
        h.expect(r[1][1].name).equals("T_xx")
        h.expect(r[1][2].name).equals("T_xy")
        h.expect(r[2][1].name).equals("T_yx")
    end)
end)

h.describe("resolve: dot product expansion", function()
    h.it("u.v dot produces scalar sum of products", function()
        local u = Node.vector("u")
        local v = Node.vector("v")
        local d = u:dot(v)
        h.expect(d.kind).equals("dot")
        local r = resolve.resolve(d, 2)
        h.expect(r.rank).equals(0)
        h.expect(r.kind).not_equals("dot")
    end)

    h.it("2D dot expands to 2 terms", function()
        local u = Node.vector("u")
        local v = Node.vector("v")
        local r = resolve.resolve(u:dot(v), 2)
        -- u_x*v_x + u_y*v_y — top-level should be add
        h.expect(r.kind).equals("add")
    end)
end)

h.describe("resolve: scale distributes", function()
    h.it("scalar * vector component has scalar factor", function()
        local s = Node.scalar("rho")
        local v = Node.vector("U")
        local n = s * v
        h.expect(n.kind).equals("scale")
        local r = resolve.resolve(n, 2)
        h.expect(#r).equals(2)
        h.expect(r[1].rank).equals(0)
    end)
end)

h.describe("resolve: grad resolves to gradient component symbols", function()
    h.it(
        "grad(scalar) resolves to vector of grad_<field>_<axis> symbols",
        function()
            local p = Node.scalar("p")
            local gp = ops.grad(p)

            h.expect(gp.rank).equals(1)

            local r = resolve.resolve(gp, 2)

            h.expect(#r).equals(2)
            h.expect(r[1].kind).equals("symbol")
            h.expect(r[2].kind).equals("symbol")
            h.expect(r[1].name).equals("grad_p_x")
            h.expect(r[2].name).equals("grad_p_y")
        end
    )

    h.it("grad(scalar) resolves to three component symbols in 3D", function()
        local p = Node.scalar("p")
        local r = resolve.resolve(ops.grad(p), 3)

        h.expect(#r).equals(3)
        h.expect(r[1].name).equals("grad_p_x")
        h.expect(r[2].name).equals("grad_p_y")
        h.expect(r[3].name).equals("grad_p_z")
    end)
end)

h.describe("resolve: ddt and laplacian pass through as abstract", function()
    h.it("ddt of scalar stays as ddt node", function()
        local p = Node.scalar("p")
        local d = ops.ddt(p)
        local r = resolve.resolve(d, 2)
        h.expect(r.kind).equals("ddt")
        h.expect(r.rank).equals(0)
    end)

    h.it("laplacian of scalar stays as laplacian node", function()
        local p = Node.scalar("p")
        local l = ops.laplacian(p)
        local r = resolve.resolve(l, 2)
        h.expect(r.kind).equals("laplacian")
        h.expect(r.rank).equals(0)
    end)

    h.it("ddt of vector resolves per component", function()
        local U = Node.vector("U")
        local d = ops.ddt(U)
        local r = resolve.resolve(d, 2)
        h.expect(#r).equals(2)
        h.expect(r[1].kind).equals("ddt")
    end)
end)

h.describe("resolve: ndims validation", function()
    h.it("ndims=1 errors", function()
        local p = Node.scalar("p")
        h.expect(function()
            resolve.resolve(p, 1)
        end).throws()
    end)

    h.it("ndims=4 errors", function()
        local p = Node.scalar("p")
        h.expect(function()
            resolve.resolve(p, 4)
        end).throws()
    end)
end)

h.describe("resolve: componentwise division", function()
    h.it("vector / scalar resolves each component over scalar", function()
        local U = Node.vector("U")
        local a = Node.scalar("a")

        local r = resolve.resolve(U / a, 2)

        h.expect(#r).equals(2)

        h.expect(r[1].kind).equals("div")
        h.expect(r[1].rank).equals(0)
        h.expect(r[1].a.name).equals("U_x")
        h.expect(r[1].b.name).equals("a")

        h.expect(r[2].kind).equals("div")
        h.expect(r[2].rank).equals(0)
        h.expect(r[2].a.name).equals("U_y")
        h.expect(r[2].b.name).equals("a")
    end)

    h.it("vector / vector resolves componentwise", function()
        local U = Node.vector("U")
        local D = Node.vector("D")

        local r = resolve.resolve(U / D, 2)

        h.expect(#r).equals(2)

        h.expect(r[1].kind).equals("div")
        h.expect(r[1].rank).equals(0)
        h.expect(r[1].a.name).equals("U_x")
        h.expect(r[1].b.name).equals("D_x")

        h.expect(r[2].kind).equals("div")
        h.expect(r[2].rank).equals(0)
        h.expect(r[2].a.name).equals("U_y")
        h.expect(r[2].b.name).equals("D_y")
    end)

    h.it("3D vector / vector resolves all components", function()
        local U = Node.vector("U")
        local D = Node.vector("D")

        local r = resolve.resolve(U / D, 3)

        h.expect(#r).equals(3)
        h.expect(r[1].b.name).equals("D_x")
        h.expect(r[2].b.name).equals("D_y")
        h.expect(r[3].b.name).equals("D_z")
    end)
end)

h.describe("resolve: SIMPLE correction expression", function()
    h.it("resolves cV * grad(p_prime) / U:diag() componentwise", function()
        local nb = require("jnl.fvm.nabla")

        local U = Node.vector("U")
        local p_prime = Node.scalar("p_prime")

        local expr = U - nb.cV() * ops.grad(p_prime) / U:diag()
        local r = resolve.resolve(expr, 2)

        h.expect(#r).equals(2)
        h.expect(r[1].rank).equals(0)
        h.expect(r[2].rank).equals(0)
    end)
end)
