#ifndef JNL_POLYMESH2D_H
#define JNL_POLYMESH2D_H

#include "jnl/common.h"
#include "jnl/arena.h"

#define JNL_PMSH2D_NAME_CAP 64
#define JNL_PMSH2D_DEFAULT_TOL 1e-12

/*
 * jnl_polymesh2d - solver-facing 2D finite-volume polymesh
 *
 * GENERATOR CONTRACT
 * ==================
 *
 * Generators/importers do not construct faces directly. They construct a
 * jnl_polymesh2d_desc containing:
 *
 *   - vertices
 *   - real cells as polygon vertex lists
 *   - cell region markers
 *   - labelled geometric edges for patches/baffles
 *
 * jnl_polymesh2d_build() lowers this description into the solver mesh.
 *
 *
 * CELL LAYOUT
 * ===========
 *
 * Cells are stored in two contiguous blocks:
 *
 *   [0, n_real_cells)      real physical cells
 *   [n_real_cells, n_cells) ghost cells generated by the builder
 *
 * Only real cells are conservation volumes. Ghost cells are stencil/BC cells.
 *
 *
 * FACE LAYOUT
 * ===========
 *
 * Faces are stored in contiguous blocks:
 *
 *   [0, n_internal_faces)
 *       internal real-real faces
 *
 *   [n_internal_faces, n_internal_faces + n_boundary_faces)
 *       boundary faces: owner is real, neighbour is ghost
 *
 *   [n_internal_faces + n_boundary_faces, n_faces)
 *       baffle/interface directed faces: owner is real, neighbour is ghost
 *
 * Every face has a valid owner and neighbour. No negative neighbour encoding is
 * used. Face normals point from owner to neighbour.
 *
 *
 * BAFFLES
 * =======
 *
 * A baffle geometric edge shared by two real cells lowers to two directed
 * faces, one per side. Each directed face has its own ghost neighbour.
 *
 * paired_face[f] gives the opposite directed face, or -1 if none.
 *
 *
 * PATCHES/REGIONS
 * ================
 *
 * Patches, baffles and regions are identified by compact internal IDs.
 * Markers are external generator/importer tags.
 *
 *
 * GEOMETRY
 * ========
 *
 * cell_vol is the 2D cell area.
 * face_area is the edge length.
 *
 * owner_face_dist[f] is the projected normal distance from owner cell centre to
 * face centre. It is useful for wall functions and boundary stencils.
 */

//
// Description/input mesh
//

enum jnl_pmsh2d_desc_edge_kind {
	JNL_PMSH2D_DESC_EDGE_BOUNDARY = 0,
	JNL_PMSH2D_DESC_EDGE_BAFFLE = 1,
};

struct jnl_pmsh2d_desc_edge {
	i32 v0, v1;
	enum jnl_pmsh2d_desc_edge_kind kind;
	i32 marker;
};

struct jnl_pmsh2d_desc_name {
	i32 marker;
	char name[JNL_PMSH2D_NAME_CAP];
};

struct jnl_polymesh2d_desc {
	i32 n_vertices;
	f64 *vx, *vy;

	i32 n_cells;
	i32 *cell_marker;

	i32 *cell_vertex_start;
	i32 *cell_vertex_list;

	i32 n_edges;
	struct jnl_pmsh2d_desc_edge *edges;

	i32 n_patch_names;
	struct jnl_pmsh2d_desc_name *patch_names;

	i32 n_baffle_names;
	struct jnl_pmsh2d_desc_name *baffle_names;

	i32 n_region_names;
	struct jnl_pmsh2d_desc_name *region_names;
};

//
// Solver mesh
//

enum jnl_pmsh2d_cell_kind {
	JNL_PMSH2D_CELL_REAL = 0,
	JNL_PMSH2D_CELL_GHOST = 1,
};

enum jnl_pmsh2d_face_kind {
	JNL_PMSH2D_FACE_INTERNAL = 0,
	JNL_PMSH2D_FACE_BOUNDARY = 1,
	JNL_PMSH2D_FACE_BAFFLE = 2,
};

struct jnl_pmsh2d_topo {
	i32 n_vertices;
	f64 *vx, *vy;

	i32 n_cells;
	i32 n_real_cells;
	i32 n_ghost_cells;

	u8 *cell_kind;
	i32 *cell_region;
	i32 *cell_marker;

	i32 *cell_vertex_start;
	i32 *cell_vertex_list;

	i32 *cell_face_start;
	i32 *cell_face_list;
	i8 *cell_face_sign;

	i32 n_faces;
	i32 n_internal_faces;
	i32 n_boundary_faces;
	i32 n_baffle_faces;

	i32 *face_vertex;

	i32 *owner;
	i32 *neighbour;

	u8 *face_kind;
	i32 *face_patch;
	i32 *face_baffle;
	i32 *paired_face;
};

struct jnl_pmsh2d_geom {
	f64 *face_cx, *face_cy;
	f64 *face_nx, *face_ny;
	f64 *face_area;

	f64 *cell_cx, *cell_cy;
	f64 *cell_vol;

	f64 *d_x, *d_y;
	f64 *d_mag;
	f64 *normal_delta;

	f64 *owner_face_dist;
};

struct jnl_pmsh2d_interp {
	f64 *face_lerp;
	f64 *delta_coeff;

	f64 *nonorth_x, *nonorth_y;
	f64 *skew_x, *skew_y;
};

struct jnl_pmsh2d_patch {
	char name[JNL_PMSH2D_NAME_CAP];
	i32 marker;

	i32 start_face;
	i32 n_faces;
};

struct jnl_pmsh2d_patches {
	i32 n_patches;
	struct jnl_pmsh2d_patch *data;
};

struct jnl_pmsh2d_region {
	char name[JNL_PMSH2D_NAME_CAP];
	i32 marker;

	i32 start_cell;
	i32 n_cells;
};

struct jnl_pmsh2d_regions {
	i32 n_regions;
	struct jnl_pmsh2d_region *data;
};

struct jnl_pmsh2d_baffle {
	char name[JNL_PMSH2D_NAME_CAP];
	i32 marker;

	i32 start_face;
	i32 n_faces;

	i32 n_pairs;
	i32 *face0;
	i32 *face1;
};

struct jnl_pmsh2d_baffles {
	i32 n_baffles;
	i32 n_baffle_faces;
	struct jnl_pmsh2d_baffle *data;
};

struct jnl_polymesh2d {
	struct jnl_pmsh2d_topo topo;
	struct jnl_pmsh2d_geom geom;
	struct jnl_pmsh2d_interp interp;

	struct jnl_pmsh2d_patches patches;
	struct jnl_pmsh2d_regions regions;
	struct jnl_pmsh2d_baffles baffles;

	jnl_arena *arena;
};

//
// Error Enum
//

enum jnl_mesh_err {
	JNL_MESH_OK = 0,

	// Generic
	JNL_MESH_ERR_ALLOC,
	JNL_MESH_ERR_INVALID_INPUT,
	JNL_MESH_ERR_UNSUPPORTED,
	JNL_MESH_ERR_INTERNAL,

	// Marker / metadata errors
	JNL_MESH_ERR_UNKNOWN_PATCH,
	JNL_MESH_ERR_UNKNOWN_BAFFLE,
	JNL_MESH_ERR_UNKNOWN_REGION,
	JNL_MESH_ERR_DUPLICATE_MARKER,

	// Topology errors
	JNL_MESH_ERR_IMPORT_FAILED,
	JNL_MESH_ERR_UNLABELLED_BOUNDARY,
	JNL_MESH_ERR_EDGE_NOT_FOUND,
	JNL_MESH_ERR_DUPLICATE_EDGE_LABEL,
	JNL_MESH_ERR_NONMANIFOLD_EDGE,
	JNL_MESH_ERR_INVALID_BOUNDARY_EDGE,
	JNL_MESH_ERR_INVALID_BAFFLE_EDGE,

	// Geometry errors
	JNL_MESH_ERR_DEGENERATE_CELL,
	JNL_MESH_ERR_DEGENERATE_FACE,
	JNL_MESH_ERR_INVALID_ORIENTATION,
};

const char *jnl_mesh_err_str(enum jnl_mesh_err err);

//
// Build/lifecycle
//

enum jnl_mesh_err jnl_polymesh2d_build(const struct jnl_polymesh2d_desc *desc,
                                       struct jnl_polymesh2d **out_mesh);

enum jnl_mesh_err
jnl_polymesh2d_desc_check(const struct jnl_polymesh2d_desc *desc);

enum jnl_mesh_err jnl_polymesh2d_check(const struct jnl_polymesh2d *mesh);

void jnl_polymesh2d_desc_free(struct jnl_polymesh2d_desc *mesh);
void jnl_polymesh2d_free(struct jnl_polymesh2d *mesh);

#endif
