---@meta
-- core/types.lua - LuaLS type declarations for jnl
-- <jed@nelson.ac> // 2026-05-22

--
-- C userdata types
--

---Vec userdata: a flat f64 array exposed to Lua, backed by C.
---@class VecUD
---@field fill      fun(self: VecUD, val: number)
---@field copy_from fun(self: VecUD, src: VecUD)
---@field norm      fun(self: VecUD): number
---@field max       fun(self: VecUD): number
---@field min       fun(self: VecUD): number
---@field sum       fun(self: VecUD): number
---@field mean      fun(self: VecUD): number
---@field scale     fun(self: VecUD, alpha: number)
---@field axpy      fun(self: VecUD, alpha: number, w: VecUD)
---@field clamp     fun(self: VecUD, lo: number, hi: number)
---@field dot       fun(self: VecUD, other: VecUD): number
